### ISSUE TITLE
Network Failure

### ISSUE THREAD

**Issue by technobrat** [skylarmt/SnipeITAPI#1]
I am trying to setup mobile access to SinpeIT.  However, I keep getting **network failure**. I have checked my settings in the database.php file and they are correct.  i have downloaded the dependencies via "composer install'.  When I attempt to access the api folder via a computer I do not get the json message; rather I get the standard 404 error with  a link that points to http://loclhost .

 Any suggestions?

**Comment by skylarmt** [comment]
A 404 is expected, as there is no index file in the folder.

What happens when you go to http://your.api.url/login.php in a browser?

**Comment by skylarmt** [comment]
If you get a 404 error when accessing login.php, there is something wrong with your web server configuration.

If you are installing this API inside the main SnipeIT install, SnipeIT might be interfering.  You can try installing this API inside a new subfolder of the SnipeIT public folder.

**Comment by technobrat** [comment]
Thanks I will try your suggestion.

**Comment by technobrat** [comment]
Ok I am able to log into the app. However it does not display the records in the database.  However, if we attempt to scan an item in, search for a record etc it says "An error occurred check your connection". No records points to a database issue, however the user name and password authenticated so there is a database connect.on. Any suggestions?

**Comment by skylarmt** [comment]
The database schema has probably changed since this API was written.  I'll look into it.
